kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rsr-media-disk-staging
  labels:
    app: rsr-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi